Merged PR 14870669: Clang: Fix common/duplicated symbols.
```
lld-link: error: duplicate symbol: gEventIndexDiscarded
>>> defined at Q:\src\hyperv.uefi\MsvmPkg\VmbfsDxe\VmbfsDxe.c
>>>            VmbfsDxe.lib(VmbfsDxe.obj)
>>> defined at Q:\src\hyperv.uefi\MsvmPkg\VmbfsDxe\VmbfsFile.c
>>>            VmbfsDxe.lib(VmbfsFile.obj)

ld-link: warning: /align specified without /driver; image may not run
lld-link: error: duplicate symbol: mInternalEventServices
>>> defined at Q:\src\hyperv.uefi\MsvmPkg\Library\EmclLib\EmclLib.c
>>>            EmclLib.lib(EmclLib.obj)
>>> defined at Q:\src\hyperv.uefi\MsvmPkg\NetvscDxe\NetvscDxe.c
>>>            NetvscDxe.lib(NetvscDxe.obj)
```
etc.

One thing may be controversial is I used `__declspec(selectany)` instead of perhaps `static`.
This is probably more like the original, and more efficient.
There's only of each, any set, gets them "all", instead of getting them multiple times.
Oh and it should be in some common header to ensure it always has the same type.

Alternatively, we could sprinkle `__declspec (selectany)` all over for these fixes.
Alternatively, put these all into a library and remove the non-standard `__declspec (selectany)`.
Call is MsGlobals? MsGlobalVariables?

I am surprised this did not build with Clang.

Related work items: #57987809, #60275790